# Generated by Django 3.1 on 2020-09-03 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('karobar', '0004_auto_20200903_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsreceived',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
