# Generated by Django 3.1 on 2020-09-03 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('karobar', '0005_auto_20200903_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
